D = input('Digite algo\n')
print("O tipo primitivo deste valor é",type(D))
print(D.isalnum())
print(D.isalpha())
print(D.isascii())
print(D.isdecimal())
print(D.isdigit())
print(D.isidentifier())
print('É só de minusculas ?',D.islower())
print(D.isnumeric())
print(D.isprintable())
print('É feito só de espaços ?',D.isspace())
print("É tudo maiusculo ?",D.isupper())